'use strict';
(function initializeArticles(window) {
  const STORAGE_KEY = 'postiq_articles_v1';
  const PLATFORMS = ['LinkedIn', 'Medium', 'Blog', 'Newsletter', 'Other'];
  let articles = []; let activeSource = null; let initialized = false;
  const el = id => document.getElementById(id);
  const text = value => String(value ?? '').trim();
  const uid = () => `article_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const now = () => new Date().toISOString();
  const safe = value => window.safeText ? window.safeText(value) : text(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function safeUrl(value) { try { const url = new URL(text(value), location.origin); return ['http:', 'https:'].includes(url.protocol) ? url.href : ''; } catch { return ''; } }
  function normalize(value = {}) { const createdAt = value.createdAt || now(); return { id: text(value.id) || uid(), title: text(value.title) || 'Untitled article', platform: PLATFORMS.includes(value.platform) ? value.platform : 'Other', url: safeUrl(value.url), publishedAt: text(value.publishedAt), content: String(value.content || ''), summary: text(value.summary), tags: Array.isArray(value.tags) ? value.tags.map(text).filter(Boolean) : text(value.tags).split(',').map(text).filter(Boolean), longformDraftId: text(value.longformDraftId), createdAt, updatedAt: value.updatedAt || createdAt }; }
  function load() { try { const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); articles = Array.isArray(parsed) ? parsed.map(normalize) : []; } catch { articles = []; } }
  function persist() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(articles)); } catch {} window.dispatchEvent(new CustomEvent('postiq:articles-changed')); }
  function upsert(value) { const article = normalize(value); const index = articles.findIndex(item => item.id === article.id || (article.longformDraftId && item.longformDraftId === article.longformDraftId)); if (index < 0) articles.unshift(article); else articles[index] = normalize({ ...articles[index], ...article, id: articles[index].id, createdAt: articles[index].createdAt, updatedAt: now() }); persist(); render(); return index < 0 ? articles[0] : articles[index]; }
  function get(id) { return articles.find(item => item.id === String(id)); }
  function remove(id) { const item = get(id); if (!item || !confirm(`Delete “${item.title}” from Articles?`)) return; articles = articles.filter(article => article.id !== id); persist(); render(); }
  function formatDate(value) { const date = value ? new Date(`${value}T12:00:00`) : null; return date && !Number.isNaN(+date) ? date.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : 'Date not added'; }
  function filtered() { const query = text(el('articleSearch')?.value).toLowerCase(); const platform = el('articlePlatformFilter')?.value || ''; const direction = el('articleSort')?.value === 'oldest' ? 1 : -1; return articles.filter(a => (!platform || a.platform === platform) && (!query || [a.title,a.summary,a.content,a.tags.join(' ')].join(' ').toLowerCase().includes(query))).sort((a,b) => direction * (new Date(a.publishedAt || a.createdAt) - new Date(b.publishedAt || b.createdAt))); }
  function render() { const list = el('articleList'), empty = el('articleEmpty'); if (!list) return; const items = filtered(); if (empty) empty.style.display = articles.length ? 'none' : 'block'; list.innerHTML = items.map(a => `<article class="article-card"><div class="article-meta">${safe(a.platform)} · ${safe(formatDate(a.publishedAt))}</div><h2>${safe(a.title)}</h2>${a.url ? `<a class="article-url" href="${safe(a.url)}" target="_blank" rel="noopener noreferrer">${safe(a.url)}</a>` : ''}${a.summary ? `<div class="article-summary">${safe(a.summary)}</div>` : ''}<div class="article-tags">${a.tags.map(tag => `<span class="article-tag">${safe(tag)}</span>`).join('')}</div><div class="article-actions">${a.url ? `<a class="btn sm primary" href="${safe(a.url)}" target="_blank" rel="noopener noreferrer">Open Article ↗</a><button class="btn sm" data-article-copy="${safe(a.id)}">Copy URL</button>` : ''}<button class="btn sm" data-article-reference="${safe(a.id)}">Use as Reference</button><button class="btn sm" data-article-repurpose="${safe(a.id)}">Repurpose</button>${a.url ? `<button class="btn sm" data-article-promote="${safe(a.id)}">Promote</button>` : ''}<button class="btn sm ghost" data-article-edit="${safe(a.id)}">Edit</button><button class="btn sm ghost" data-article-delete="${safe(a.id)}">Delete</button></div></article>`).join(''); bindList(); }
  function openForm(value = {}) { const article = value.id ? value : normalize({ ...value, id: uid(), createdAt: now() }); el('articleId').value = article.id; el('articleUrl').value = article.url; el('articlePlatform').value = article.platform; el('articlePublishedAt').value = article.publishedAt || new Date().toISOString().slice(0,10); el('articleTitle').value = value.title || ''; el('articleContent').value = article.content; el('articleSummary').value = article.summary; el('articleTags').value = article.tags.join(', '); el('articleForm').dataset.longformDraftId = article.longformDraftId; el('articleModalTitle').textContent = value.title ? 'Edit Published Article' : 'Save Published Article'; const modal=el('articleModal'); modal.hidden=false; modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); setTimeout(()=>el('articleUrl')?.focus(),0); }
  function closeForm() { const modal=el('articleModal'); modal?.classList.remove('open'); if(modal){modal.hidden=true;modal.setAttribute('aria-hidden','true');} }
  function submit(event) { event.preventDefault(); const title=text(el('articleTitle').value), content=text(el('articleContent').value); if(!title||!content) return window.showToast?.('Add a title and article content first','error'); upsert({ id:el('articleId').value,title,content,url:el('articleUrl').value,platform:el('articlePlatform').value,publishedAt:el('articlePublishedAt').value,summary:el('articleSummary').value,tags:el('articleTags').value,longformDraftId:event.currentTarget.dataset.longformDraftId }); closeForm(); window.showToast?.('Article saved for future content','success'); }
  function context(article, max=6000) { if(!article)return null; const body=article.content.length>max ? `${article.content.slice(0,max)}\n\n[Article shortened for writing context]` : article.content; return { id:article.id,type:'article',title:article.title,body,platform:article.platform,publishedAt:article.publishedAt,url:article.url,tags:article.tags }; }
  function useReference(article) { const ref=context(article); window.pinReferenceToComposer?.(ref); window.activateView?.('composerView','article_reference'); window.showToast?.('Article pinned beside your draft','success'); }
  function supportedOptions(article, mode='repurpose') { const available=new Set(((typeof state !== 'undefined' && state.channels) || []).map(c=>window.PlatformGuidance?.key?.(c.service)||c.service)); const candidates=[['linkedin','LinkedIn post'],['threads','Threads post'],['threads','Threads thread'],['bluesky','Bluesky post'],['bluesky','Bluesky thread'],['twitter','X post / thread'],['instagram','Instagram carousel copy']].filter(([key])=>available.has(key)); const base=candidates.length?candidates:[['universal','Social post']]; if(mode==='repurpose') base.push(['followups','3 standalone follow-up posts'],['ideas','Find 5 standalone ideas'],['expand','Expand a briefly mentioned idea'],['contrarian','Contrarian follow-up'],['question','Turn a section into a discussion question'],['quote','Turn one insight into a post'],['related','Related post without a link']); else base.push(['alternate','Alternate hook'],['later','Follow-up post for several days later']); return base; }
  function openRepurpose(article, mode='repurpose') { activeSource={ article,mode }; el('repurposeTitle').textContent=mode==='promote'?'Promote Article':'Repurpose Article'; el('repurposeOptions').innerHTML=supportedOptions(article,mode).map(([key,label])=>`<button class="btn repurpose-option" data-repurpose-kind="${safe(key)}"><strong>${safe(label)}</strong><span>${mode==='promote'?'Share value first, then point naturally to the article.':'Create an editable starting point in Compose.'}</span></button>`).join(''); const modal=el('repurposeModal');modal.hidden=false;modal.classList.add('open');modal.setAttribute('aria-hidden','false'); }
  function compose(kind) { const {article,mode}=activeSource||{}; if(!article)return; const intro=mode==='promote'?`A useful idea from “${article.title}”:\n\n${article.summary||article.content.slice(0,320)}\n\n${article.url}`:`Working from “${article.title}”:\n\n${article.summary||article.content.slice(0,420)}\n\n[Develop this into: ${kind}]`; window.pinReferenceToComposer?.(context(article)); const editor=el('composerEditor'); if(editor){editor.textContent=intro;editor.dispatchEvent(new Event('input',{bubbles:true}));} closeRepurpose(); window.activateView?.('composerView','article_repurpose'); window.showToast?.('Editable draft opened in Compose','success'); }
  function closeRepurpose(){const modal=el('repurposeModal');modal?.classList.remove('open');if(modal){modal.hidden=true;modal.setAttribute('aria-hidden','true');}}
  function bindList(){ el('articleList')?.querySelectorAll('[data-article-copy]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(get(b.dataset.articleCopy)?.url||'').then(()=>window.showToast?.('URL copied','success'))); el('articleList')?.querySelectorAll('[data-article-reference]').forEach(b=>b.onclick=()=>useReference(get(b.dataset.articleReference))); el('articleList')?.querySelectorAll('[data-article-repurpose]').forEach(b=>b.onclick=()=>openRepurpose(get(b.dataset.articleRepurpose))); el('articleList')?.querySelectorAll('[data-article-promote]').forEach(b=>b.onclick=()=>openRepurpose(get(b.dataset.articlePromote),'promote')); el('articleList')?.querySelectorAll('[data-article-edit]').forEach(b=>b.onclick=()=>openForm(get(b.dataset.articleEdit))); el('articleList')?.querySelectorAll('[data-article-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.articleDelete)); }
  function init(){if(initialized)return;initialized=true;load(); document.querySelectorAll('[data-new-article]').forEach(b=>b.addEventListener('click',()=>openForm())); document.querySelectorAll('[data-close-article]').forEach(b=>b.addEventListener('click',closeForm)); document.querySelectorAll('[data-close-repurpose]').forEach(b=>b.addEventListener('click',closeRepurpose)); el('articleForm')?.addEventListener('submit',submit); ['articleSearch','articlePlatformFilter','articleSort'].forEach(id=>el(id)?.addEventListener(id==='articleSearch'?'input':'change',render)); el('repurposeOptions')?.addEventListener('click',e=>{const b=e.target.closest('[data-repurpose-kind]');if(b)compose(b.dataset.repurposeKind);}); const opts=PLATFORMS.map(p=>`<option value="${p}">${p}</option>`).join(''); el('articlePlatform').innerHTML=opts; el('articlePlatformFilter').insertAdjacentHTML('beforeend',opts); window.addEventListener('postiq:view-changed',e=>{if(e.detail?.viewId==='articlesView')render();}); render();}
  window.Articles={init,normalize,get,getAll:()=>articles.map(normalize),upsert,openForm,openRepurpose,useReference,context,STORAGE_KEY};
})(window);
