'use strict';
(function initializeLongform(window) {
  const STORAGE_KEY='postiq_longform_drafts_v1';
  const TYPES=['LinkedIn Article','Medium Story','Blog / Generic Article','Newsletter'];
  const STAGES=['angle','outline','draft','polish','publish','repurpose'];
  let drafts=[];let currentId=null;let origin='ideasView';let saveTimer=null;let initialized=false;
  const el=id=>document.getElementById(id);const text=v=>String(v??'').trim();const uid=()=>`longform_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;const now=()=>new Date().toISOString();
  function normalize(value={}){const createdAt=value.createdAt||now();return{id:text(value.id)||uid(),title:text(value.title),subtitle:text(value.subtitle),introduction:String(value.introduction||''),outline:String(value.outline||''),content:String(value.content||value.body||''),conclusion:String(value.conclusion||''),type:TYPES.includes(value.type)?value.type:TYPES[0],status:['draft','ready','published'].includes(value.status)?value.status:'draft',stage:STAGES.includes(value.stage)?value.stage:'angle',angle:String(value.angle||''),references:Array.isArray(value.references)?value.references:[],sourceLinks:String(value.sourceLinks||''),notes:String(value.notes||''),heroImage:String(value.heroImage||''),ideaId:text(value.ideaId),articleId:text(value.articleId),publishedUrl:text(value.publishedUrl),publishedAt:text(value.publishedAt),createdAt,updatedAt:value.updatedAt||createdAt};}
  function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');drafts=Array.isArray(parsed)?parsed.map(normalize):[];}catch{drafts=[];}}
  function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(drafts));}catch{}window.dispatchEvent(new CustomEvent('postiq:longform-changed'));}
  function current(){return drafts.find(d=>d.id===currentId);}
  function patch(data){const index=drafts.findIndex(d=>d.id===currentId);if(index<0)return;drafts[index]=normalize({...drafts[index],...data,updatedAt:now()});save();return drafts[index];}
  function create(input={}){const idea=input.ideaId?window.Notebook?.getCard?.(input.ideaId):null;const draft=normalize({ideaId:input.ideaId,title:input.title||idea?.title||'',angle:idea?.development?.coreThought||idea?.sourceText||'',notes:idea?.development?.notes||''});drafts.unshift(draft);save();open(draft.id,input.origin||'ideasView');return draft;}
  function open(id,from='ideasView'){currentId=id;origin=from;window.activateView?.('longformView','longform');render();}
  function stageIndex(){return Math.max(0,STAGES.indexOf(current()?.stage));}
  function field(label,name,type='input',placeholder=''){const d=current();const value=d?.[name]||'';return `<div class="field"><label class="label" for="lf-${name}">${label}</label>${type==='textarea'?`<textarea class="input ${name==='content'?'longform-body':''}" id="lf-${name}" data-lf-field="${name}" placeholder="${placeholder}">${escape(value)}</textarea>`:`<input class="input ${name==='title'?'longform-title-input':''}" id="lf-${name}" data-lf-field="${name}" value="${escape(value)}" placeholder="${placeholder}">`}</div>`;}
  function escape(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function renderProgress(){const nav=el('longformProgress');if(!nav)return;nav.innerHTML=STAGES.map((stage,i)=>`<button class="longform-step ${current()?.stage===stage?'active':''}" data-lf-stage="${stage}" aria-current="${current()?.stage===stage?'step':'false'}">${i+1}. ${stage==='publish'?'PUBLISH / EXPORT':stage.toUpperCase()}</button>`).join('');nav.querySelectorAll('[data-lf-stage]').forEach(b=>b.onclick=()=>{flush();patch({stage:b.dataset.lfStage});render();});}
  function intro(){const d=current();return `<div class="longform-fields"><div class="field"><label class="label" for="lf-type">Longform destination</label><select class="input" id="lf-type" data-lf-field="type">${TYPES.map(t=>`<option ${d.type===t?'selected':''}>${t}</option>`).join('')}</select></div>${field('Working angle','angle','textarea','What is the clearest point of view?')}${field('Title','title','input','A title readers will understand')}${field('Subtitle / deck','subtitle','input','Optional context beneath the title')}</div>`;}
  function outline(){return `<div class="longform-fields">${field('Introduction','introduction','textarea','How will you bring the reader in?')}${field('Sections and headings','outline','textarea','One section per line…')}<details class="optional-fields"><summary>References and notes</summary>${field('Source / reference links','sourceLinks','textarea','One URL per line')}${field('Notes','notes','textarea','Anything you want to remember')}${field('Hero-image reference','heroImage','input','Image URL, brief, or credit')}</details></div>`;}
  function draft(){return `<div class="longform-fields">${field('Title','title')}${field('Subtitle / deck','subtitle')}${field('Article body','content','textarea','Write freely. Your draft saves locally as you type…')}${field('Conclusion / CTA','conclusion','textarea','Leave the reader with a useful next thought or action.')}</div>`;}
  function polish(){const d=current();const words=[d.introduction,d.content,d.conclusion].join(' ').trim().split(/\s+/).filter(Boolean).length;return `<div class="longform-fields">${field('Title','title')}${field('Subtitle / deck','subtitle')}${field('Introduction','introduction','textarea')}${field('Polished body','content','textarea')}${field('Conclusion / CTA','conclusion','textarea')}<div class="article-meta">${words} words · Check the opening, transitions, evidence, and ending.</div></div>`;}
  function fullText(d=current()){return [d.title,d.subtitle,d.introduction,d.content,d.conclusion].filter(text).join('\n\n');}
  function publish(){const d=current();const linked=d.type==='LinkedIn Article',medium=d.type==='Medium Story';const destination=linked?'LinkedIn':medium?'Medium':d.type;const openUrl=linked?'https://www.linkedin.com/article/new/':medium?'https://medium.com/new-story':'';return `<div class="publish-panel"><h3>Ready for ${escape(destination)}</h3><p class="page-desc">PostIQ prepares the handoff. Publishing happens on the destination itself.</p><div class="copy-grid"><button class="btn" data-copy-part="title">Copy Title</button>${d.subtitle?'<button class="btn" data-copy-part="subtitle">Copy Subtitle</button>':''}<button class="btn" data-copy-part="body">Copy Body</button><button class="btn primary" data-copy-part="all">Copy All</button>${!linked&&!medium?'<button class="btn" data-copy-part="markdown">Copy Markdown</button><button class="btn" data-copy-part="plain">Copy Plain Text</button>':''}${openUrl?`<a class="btn ghost" href="${openUrl}" target="_blank" rel="noopener noreferrer">Open ${destination} ↗</a>`:''}</div></div><div class="publish-panel"><h3>Article published?</h3><p class="page-desc">Save the live URL so PostIQ can reference and promote it later.</p><div class="row"><input class="input grow" id="lf-publishedUrl" type="url" value="${escape(d.publishedUrl)}" placeholder="https://…"><button class="btn success" id="lf-mark-published">Mark as Published</button></div>${d.articleId?'<div class="row mt8"><button class="btn" data-after-publish="view">View Article</button><button class="btn" data-after-publish="repurpose">Repurpose</button><button class="btn" data-after-publish="promote">Promote</button></div>':''}</div>`;}
  function repurpose(){const d=current();return `<div class="publish-panel"><h3>One good idea can become an entire body of content.</h3><p class="page-desc">Turn this longform piece into editable social drafts or extract a fresh follow-up idea.</p><button class="btn primary" id="lf-repurpose">Repurpose Longform</button>${d.publishedUrl?'<button class="btn" id="lf-promote">Promote Article</button>':''}</div>`;}
  function render(){const d=current();if(!d)return;el('longformHeading').textContent=d.title||'Untitled longform';el('longformSaveState').textContent=`${d.status==='published'?'Published':'Saved locally'} · updated ${new Date(d.updatedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`;renderProgress();const labels={angle:['Choose the angle','Start with a clear destination and point of view.'],outline:['Shape the outline','Build a path before filling every paragraph.'],draft:['Write the draft','Stay focused on the words; supporting controls remain tucked away.'],polish:['Polish the article','Read the complete piece and tighten it for publication.'],publish:['Publish / Export','Copy a reliable handoff to the native destination.'],repurpose:['Repurpose','Keep getting value from your strongest thinking.']};const [title,copy]=labels[d.stage];const bodies={angle:intro,outline,draft,polish,publish,repurpose};el('longformEditor').innerHTML=`<article class="longform-editor-card"><h2>${title}</h2><p class="page-desc">${copy}</p>${bodies[d.stage]()}<div class="longform-stage-actions"><button class="btn ghost" id="lf-prev" ${stageIndex()===0?'disabled':''}>← Previous</button><button class="btn primary" id="lf-next" ${stageIndex()===STAGES.length-1?'disabled':''}>${d.stage==='polish'?'Continue to Publish / Export':'Save & Continue →'}</button></div></article>`;bindEditor();}
  function bindEditor(){el('longformEditor')?.querySelectorAll('[data-lf-field]').forEach(input=>input.addEventListener('input',()=>{clearTimeout(saveTimer);el('longformSaveState').textContent='Saving…';saveTimer=setTimeout(()=>{patch({[input.dataset.lfField]:input.value});el('longformHeading').textContent=current().title||'Untitled longform';el('longformSaveState').textContent='Saved locally';},250);}));el('lf-prev')?.addEventListener('click',()=>move(-1));el('lf-next')?.addEventListener('click',()=>move(1));el('longformEditor')?.querySelectorAll('[data-copy-part]').forEach(b=>b.onclick=()=>copyPart(b.dataset.copyPart));el('lf-mark-published')?.addEventListener('click',markPublished);el('lf-repurpose')?.addEventListener('click',()=>repurposeCurrent('repurpose'));el('lf-promote')?.addEventListener('click',()=>repurposeCurrent('promote'));el('longformEditor')?.querySelectorAll('[data-after-publish]').forEach(b=>b.onclick=()=>afterPublish(b.dataset.afterPublish));}
  function flush(){clearTimeout(saveTimer);const data={};el('longformEditor')?.querySelectorAll('[data-lf-field]').forEach(i=>data[i.dataset.lfField]=i.value);if(Object.keys(data).length)patch(data);}
  function move(offset){flush();const next=Math.max(0,Math.min(STAGES.length-1,stageIndex()+offset));patch({stage:STAGES[next],status:next>=4?'ready':current().status});render();window.scrollTo({top:0,behavior:'smooth'});}
  function copyPart(part){const d=current();const values={title:d.title,subtitle:d.subtitle,body:[d.introduction,d.content,d.conclusion].filter(text).join('\n\n'),all:fullText(d),plain:fullText(d),markdown:`# ${d.title}\n\n${d.subtitle?`_${d.subtitle}_\n\n`:''}${d.introduction}\n\n${d.content}\n\n${d.conclusion}`};navigator.clipboard.writeText(values[part]||'').then(()=>window.showToast?.('Copied for publishing','success'));}
  function markPublished(){flush();const d=current(),url=text(el('lf-publishedUrl')?.value);if(!url)return window.showToast?.('Paste the live article URL first','error');const article=window.Articles?.upsert({id:d.articleId||undefined,title:d.title,platform:d.type.startsWith('LinkedIn')?'LinkedIn':d.type.startsWith('Medium')?'Medium':d.type.startsWith('Newsletter')?'Newsletter':'Blog',url,publishedAt:new Date().toISOString().slice(0,10),content:[d.introduction,d.content,d.conclusion].filter(text).join('\n\n'),summary:d.subtitle,tags:[],longformDraftId:d.id});patch({status:'published',publishedUrl:url,publishedAt:article.publishedAt,articleId:article.id});window.showToast?.('Published article saved to your library','success');render();}
  function sourceArticle(){const d=current();return d.articleId?window.Articles?.get(d.articleId):window.Articles?.normalize({title:d.title,content:fullText(d),summary:d.subtitle,url:d.publishedUrl,platform:d.type.startsWith('LinkedIn')?'LinkedIn':'Other',longformDraftId:d.id});}
  function repurposeCurrent(mode){window.Articles?.openRepurpose(sourceArticle(),mode);}
  function afterPublish(action){if(action==='view')window.activateView?.('articlesView');else repurposeCurrent(action);}
  function renderDraftList(){const list=el('longformDraftList');if(!list)return;list.innerHTML=drafts.length?drafts.slice(0,6).map(d=>`<button class="btn" type="button" data-open-longform="${escape(d.id)}">${escape(d.title||'Untitled longform')} · ${escape(d.status)}</button>`).join(''):'<span class="article-meta">No longform drafts yet.</span>';list.querySelectorAll('[data-open-longform]').forEach(b=>b.onclick=()=>open(b.dataset.openLongform,'articlesView'));}
  function init(){if(initialized)return;initialized=true;load();renderDraftList();window.addEventListener('postiq:longform-changed',renderDraftList);el('newLongformBtn')?.addEventListener('click',()=>create({origin:'articlesView'}));el('longformBack')?.addEventListener('click',()=>{flush();window.activateView?.(origin);});el('longformLibraryBtn')?.addEventListener('click',()=>{flush();window.activateView?.('articlesView');});el('contentDetailLongform')?.addEventListener('click',()=>{const idea=window.ContentDetail?.getCurrent?.();create({ideaId:idea?.id,origin:'contentDetailView'});});}
  window.Longform={init,normalize,create,open,getAll:()=>drafts.map(normalize),STORAGE_KEY};
})(window);
